version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: geopolitical_data_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geopolitical_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  dagster:
    build: ./dagster_project
    ports:
      - 3000:3000
    depends_on: postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    volumes:
      - ./dagster_project:/app
      - ./data:/data

  dbt:
    build: ./dbt_project
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
    volumes:
      - ./dbt_project:/dbt

volumes:
  postgres_data: