geopolitical_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DATABASE_HOST', 'localhost') }}"
      port: "{{ env_var('DATABASE_PORT', 5432) | as_number }}"
      user: "{{ env_var('DATABASE_USER', 'postgres') }}"
      password: "{{ env_var('DATABASE_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('DATABASE_NAME', 'geopolitical_platform') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
